server:
  port: 8082
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: priceapi
  datasource:
    driverClassName: org.h2.Driver
    password: toor
    testWhileIdle: true
    url: jdbc:h2:mem:itemsdb
    username: admin
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-ui
